from enum import Enum


# Abstract Syntax Tree Node Type
class ASTNodeType(Enum):
    # Program
    STMT_LIST = "STATEMENT LIST"

    # Statements
    ASS_STMT = "ASSIGNMENT STATEMENT"
    EXP_STMT = "EXPRESSION STATEMENT"
    CLR_STMT = "CLEAR STATEMENT"
    SEL_STMT = "SELECTION STATEMENT"
    ITR_STMT = "ITERATION STATEMENT"
    JMP_STMT = "JUMP STATEMENT"

    # Statement Components
    EO_STMT = "END OF STATEMENT"
    ID_LIST = "IDENTIFIER LIST"
    SEL_ClS = "SELECTION CLAUSE"
    FOR_CLS = "FOR CLAUSE"
    WHL_CLS = "WHILE CLAUSE"

    # Expressions
    ASS_EXP = "ASSIGNMENT EXPRESSION"
    CLN_EXP = "COLON EXPRESSION"
    BSO_EXP = "BINARY SCALAR OPERATOR EXPRESSION"
    MML_EXP = "MATRIX MULTIPLICATION EXPRESSION"
    MRD_EXP = "MATRIX RIGHT DIVISION EXPRESSION"
    MLD_EXP = "MATRIX LEFT DIVISION EXPRESSION"
    USO_EXP = "UNARY SCALAR OPERATOR EXPRESSION"
    PRI_EXP = "PRIMARY EXPRESSION"

    # Literals
    NUM_LIT = "NUMBER LITERAL"
    STR_LIT = "STRING LITERAL"

    ID = "IDENTIFIER"
